### ISSUE TITLE
TPCC Errors Post-Recovery in Master Branch

### ISSUE THREAD

**Issue by cdcsl** [leanstore/leanstore#14]
Hi there,

When running TPCC in the master branch with the following populate command

`./frontend/tpcc --ssd_path=/mnt/dbs/tpcc --worker_threads=60 --pp_threads=10 --wal_log_writers=10 --dram_gib=200 --tpcc_warehouse_count=1000 --notpcc_warehouse_affinity --csv_path=./log  --free_pct=1 --contention_split --xmerge --print_tx_console --isolation_level=si --persist=true --wal=true --wal_pwrite=true --wal_offset_gib=200 --recover=false --persist_file=leanstore.json --run_for_seconds=1`

Then recovering and running the workload with the following command

`./frontend/tpcc --ssd_path=/mnt/dbs/tpcc --worker_threads=60 --pp_threads=10 --wal_log_writers=10 --dram_gib=200 --tpcc_warehouse_count=1000 --notpcc_warehouse_affinity --csv_path=./log  --free_pct=1 --contention_split --xmerge --print_tx_console --isolation_level=si --persist=false --wal=true --wal_pwrite=true --wal_offset_gib=200 --recover=true --recover_file=leanstore.json --run_for_seconds=60`

I'm unable to get a run that lasts more than a few seconds.

I see a couple of consistent segmentation faults in Latch.hpp and ConcurrencyControl.cpp, stack traces below.

<pre>
[0] from 0x00005555559666f4 in std::__atomic_base<unsigned long>::load(std::memory_order) const+39 at /usr/include/c++/11/bits/atomic_base.h:488
[1] from 0x00005555559666f4 in leanstore::storage::Guard::toOptimisticOrJump()+278 at /home/me/leanstore/backend/leanstore/sync-primitives/Latch.hpp:121
[2] from 0x0000555555b0c867 in leanstore::storage::BMOptimisticGuard::BMOptimisticGuard(leanstore::storage::HybridLatch&)+51 at /home/me/leanstore/backend/leanstore/storage/buffer-manager/BMPlainGuard.hpp:31
[3] from 0x0000555555b079e7 in leanstore::storage::BufferManager::resolveSwip(leanstore::storage::Guard&, leanstore::storage::Swip<leanstore::storage::BufferFrame>&)+563 at /home/me/leanstore/backend/leanstore/storage/buffer-manager/BufferManager.cpp:290
[4] from 0x0000555555968315 in leanstore::storage::BufferManager::tryFastResolveSwip(leanstore::storage::Guard&, leanstore::storage::Swip<leanstore::storage::BufferFrame>&)+97 at /home/me/leanstore/backend/leanstore/storage/buffer-manager/BufferManager.hpp:119
[5] from 0x0000555555979ffd in leanstore::storage::HybridPageGuard<leanstore::storage::btree::BTreeNode>::HybridPageGuard<leanstore::storage::btree::BTreeNode>(leanstore::storage::HybridPageGuard<leanstore::storage::btree::BTreeNode>&, leanstore::storage::Swip<leanstore::storage::btree::BTreeNode>&, leanstore::storage::LATCH_FALLBACK_MODE)+107 at /home/me/leanstore/backend/leanstore/sync-primitives/PageGuard.hpp:76
[6] from 0x000055555597707a in leanstore::storage::btree::BTreePessimisticIterator::findLeafAndLatch<(leanstore::storage::LATCH_FALLBACK_MODE)0>(leanstore::storage::HybridPageGuard<leanstore::storage::btree::BTreeNode>&, unsigned char const*, unsigned short)+1818 at /home/me/leanstore/backend/leanstore/storage/btree/core/BTreeGenericIterator.hpp:67
[7] from 0x0000555555969b3e in leanstore::storage::btree::BTreePessimisticIterator::gotoPage(std::basic_string_view<unsigned char, std::char_traits<unsigned char> > const&)+670 at /home/me/leanstore/backend/leanstore/storage/btree/core/BTreeGenericIterator.hpp:105
[8] from 0x000055555596a584 in leanstore::storage::btree::BTreePessimisticIterator::seekExact(std::basic_string_view<unsigned char, std::char_traits<unsigned char> >)+428 at /home/me/leanstore/backend/leanstore/storage/btree/core/BTreeGenericIterator.hpp:137
[9] from 0x0000555555a8cdfc in leanstore::storage::btree::BTreeVI::lookupPessimistic(unsigned char*, unsigned short, std::function<void (unsigned char const*, unsigned short)>)+1024 at /home/me/leanstore/backend/leanstore/storage/btree/BTreeVI.cpp:42` </pre>

<pre>
#0 0x55555593650e in leanstore::cr::Worker::ConcurrencyControl::isVisibleForMe(unsigned short, unsigned long, bool) /home/me/leanstore/backend/leanstore/concurrency-recovery/ConcurrencyControl.cpp:274 
#1 0x555555acf8b5 in leanstore: :storage::btree::BTreeVI::FatTupleDifferentAttributes::reconstructTuple(std::function<void (std::basic_string_view<unsigned char, std::char_traits<unsigned char> ›)>) const /home/me/leanstore/backend/leanstore/storage/btree/FatTupleDifferentAttributes.cpp:306
#2 0x555555ab8806 in leanstore: :storage: :btree::BTreeVI: :reconstructTuple(std::basic_string_view<unsigned char, std::char_traits<unsigned char> >, std::basic_string_view<unsigned char, std::char_traits<unsigned char> >, std::function void (std::basic_string_view<unsigned char,std::char_traits<unsigned char> ›)>) (/home/me/leanstore/build/frontend/tpcc+0x564806)
#3 0x555555abaeff in leanstore::OP_RESULT leanstore: :storage: :btree::BTreeVI: :scan<false>(unsigned char*, unsigned short, std::function<bool Cunsigned char const*, unsigned short, unsigned char const*, unsigned short)>) /home/me/leanstore/backend/leanstore/storage/bree/BTreeVI.hpp:303
#4 0x555555aacc81 in leanstore::storage::btree::BTreeVI: :scanDescunsigned char*, unsigned short, std:: function<bool (unsigned char const*, unsigned short, unsigned char const*, unsigned short)>, std:: function‹ void ()>) /home/me/leanstore/backend/leanstore/storage/btree/BTreeVI.cpp: 858
#5 0x55555581f6fe in LeanStoreAdapter<history_t>::scanDescChistory_t::Key const&, std::function-bool (history_t::Key const&, history_t const&) > const&, std::function-void ()>) (/home/me/leanstore/build/frontend/tpcc+0x2cb6fe)
#6 0x555555804f11 in TPCCWorkload<LeanStoreAdapter>: :prepare() /home/me/leanstore/build/frontend/tpcc+0x2b0f11)
#7 0x5555557ea53f in operator() /home/me/leanstore/frontend/tpc-c/pcc.cp: 226
#8 0x5555557f205b in invoke_impl-void, main(int, char**):: <lambda()>&>/usr/include/c++/11/bits/invoke.h:61
#9 0x5555557f1965 in invoke_r<void, main(int, char**)::<lambda()>&>/usr/include/c++/11/bits/invoke.h:111
#10 0x5555557f059a in _M_invoke /usr/include/c++/11/bits/std_function.h:290
#11 0x55555592d611 in std:: function<void ()›::operator)( const /usr/include/c++/11/bits/std_function.h:590
#12 0x555555925096 in operator () /home/me/leanstore/backend/leanstore/concurrency-recovery/CRMG.cpp:57
#13 0x55555592c1f4 in __invoke_impl<void, leanstore::cr::CRManager::CRManager(leanstore::cr::HistoryTreeInterface&, s32, u64)::<lambda()>> /usr/include/c++/11/bits/invoke.h:61
#14 0x55555592c164 in #15 0x55555592c0e5 in-_invoke<leanstore::cr::CRManager::CRManager(leanstore::Cr::HistoryTreeInterface&, s32, u64)::<lambda()> > /usr/include/C++/11/bits/invoke.h:96 _M_invoke<0> /usr/include/c++/11/bits/std_thread.h:259
#16 0x55555592c09d in operator() /usr/include/c++/11/bits/std_thread.h:266
#17 0x55555592c05d in _M_run /usr/include/c++/11/bits/std_thread.h:211
#18 0x555555bf3323 in execute_native_thread_routine (/home/me/leanstore/build/frontend/pcc+0x69f323)
#19 0x7ffff75a1608 in start_thread /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477
#20 0x7ffff72fb132 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f132)
</pre>

Would there be some way to get around these?

Thanks.

**Comment by cdcsl** [comment]
Closing this issue as recovery is stated to not be finished on the main README. Apologies.
